### ISSUE TITLE
Make Sprint 1 Presentation

### ISSUE THREAD

**Issue by yuliabardinova** [yuliabardinova/tribler#19]

**Comment by yuliabardinova** [comment]
points to highlight:
- the chosen project is complicated
- we had to choose another feature/bugfix (explain why)
- the changed code was in the submodule, which complicated the process
- the CI/CD tests kept failing (screenshot the error)
- SonarCloud found no issues with the code, because the changed code was in the submodule
- we had to add the submodule repo to SonarCloud for analysis as well
- the Scrum process is easy to follow, it's the project that's complicated

**Comment by EliM147** [comment]
Ok, I'd do the issue and send the result to Teams

**Comment by synctext** [comment]
> the chosen project is complicated

Yes, its actually one of the more complicated pure self-organising systems ever created and used :laughing: 16 years of work.
Basically, there is Bitcoin, Bittorrent and Tribler. Not much else, _if_ you follow an academically pure definition of self-organising system (e.g. no central element at all). You are doing this for course credits? (I'm the responsible professor for Tribler at Delft University.)

**Comment by yuliabardinova** [comment]
> Yes, its actually one of the more complicated pure self-organising systems ever created and used 😆 16 years of work.
> Basically, there is Bitcoin, Bittorrent and Tribler. Not much else, _if_ you follow an academically pure definition of self-organising system (e.g. no central element at all). You are doing this for course credits? (I'm the responsible professor for Tribler at Delft University.)

Yes, this is a university project, but for Tampere University. Next step -- feature implementation
