### ISSUE TITLE
Choose feature

### ISSUE THREAD

**Issue by yuliabardinova** [yuliabardinova/tribler#9]
We have mistakenly chosen a bug instead of a feature to implement. Now, we need to choose a proper feature. Look through the [issues with the " enhancement" label](https://github.com/Tribler/tribler/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22type%3A+enhancement%22).

Comment your suggestions

**Comment by wowaser** [comment]
https://github.com/Tribler/tribler/issues/5624 GUI checkbox contrast EASY
https://github.com/Tribler/tribler/issues/5577 HTTP headers very eASY

**Comment by yuliabardinova** [comment]
We have chosen issue #5624
